// ============================================================
// HeatWise — Cooling Module Registry
// recommendation-engine/modules.ts
// ============================================================

import type { CoolingModule } from "@/models";

export const COOLING_MODULES: CoolingModule[] = [
  {
    id:                   "modular_tray_60",
    name:                 "Modular Planter Tray 60×60cm",
    type:                 "planter",
    widthM:               0.6,
    lengthM:              0.6,
    heightM:              0.15,
    unitCost:             42,
    installCost:          8,
    coolingContributionC: 0.10,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace"],
    description:          "Pre-grown lightweight tray with self-watering reservoir.",
  },
  {
    id:                   "substrate_deep",
    name:                 "Deep Growing Substrate (per m²)",
    type:                 "planter",
    widthM:               1,
    lengthM:              1,
    heightM:              0.30,
    unitCost:             28,
    installCost:          15,
    coolingContributionC: 0.05,
    maintenanceLevel:     "minimal",
    requiresWater:        true,
    requiresStructural:   true,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop"],
    description:          "300mm engineered growing medium for intensive green roofs.",
  },
  {
    id:                   "substrate_shallow",
    name:                 "Shallow Growing Medium (per m²)",
    type:                 "planter",
    widthM:               1,
    lengthM:              1,
    heightM:              0.10,
    unitCost:             12,
    installCost:          6,
    coolingContributionC: 0.03,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop"],
    description:          "100mm extensive substrate for sedum and grass mats.",
  },
  {
    id:                   "root_barrier",
    name:                 "Root Barrier Membrane (per m²)",
    type:                 "planter",
    widthM:               1,
    lengthM:              1,
    heightM:              0.005,
    unitCost:             5,
    installCost:          3,
    coolingContributionC: 0,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop"],
    description:          "Waterproof root barrier protecting roof structure.",
  },
  {
    id:                   "irrigation_drip",
    name:                 "Drip Irrigation Kit",
    type:                 "irrigation",
    widthM:               0.1,
    lengthM:              0.1,
    heightM:              0.05,
    unitCost:             185,
    installCost:          80,
    coolingContributionC: 0.40,
    maintenanceLevel:     "minimal",
    requiresWater:        true,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace", "balcony"],
    description:          "Automated drip system with timer. Covers up to 60m².",
  },
  {
    id:                   "raised_bed_cedar",
    name:                 "Cedar Raised Bed 1.2×0.6m",
    type:                 "raised_bed",
    widthM:               1.2,
    lengthM:              0.6,
    heightM:              0.45,
    unitCost:             110,
    installCost:          25,
    coolingContributionC: 0.15,
    maintenanceLevel:     "moderate",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace"],
    description:          "Solid cedar raised bed with liner. 25-year lifespan.",
  },
  {
    id:                   "raised_bed_small",
    name:                 "Small Planter Box 60×40cm",
    type:                 "raised_bed",
    widthM:               0.6,
    lengthM:              0.4,
    heightM:              0.35,
    unitCost:             55,
    installCost:          10,
    coolingContributionC: 0.08,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace", "balcony"],
    description:          "Compact planter for herbs and small perennials.",
  },
  {
    id:                   "compost_bin",
    name:                 "Compact Compost Bin",
    type:                 "raised_bed",
    widthM:               0.5,
    lengthM:              0.5,
    heightM:              0.6,
    unitCost:             45,
    installCost:          10,
    coolingContributionC: 0,
    maintenanceLevel:     "moderate",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        20,
    compatibleSpaces:     ["rooftop", "terrace"],
    description:          "On-site composting to support food garden nutrients.",
  },
  {
    id:                   "pergola_steel",
    name:                 "Steel Pergola Frame 3×3m",
    type:                 "pergola",
    widthM:               3.0,
    lengthM:              3.0,
    heightM:              2.4,
    unitCost:             680,
    installCost:          320,
    coolingContributionC: 0.80,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   true,
    minFloorLevel:        0,
    maxFloorLevel:        15,
    compatibleSpaces:     ["terrace"],
    description:          "Powder-coated steel pergola frame for climbing plants and shade cloth.",
  },
  {
    id:                   "shade_sail_large",
    name:                 "Shade Sail 5×5m",
    type:                 "shade",
    widthM:               5.0,
    lengthM:              5.0,
    heightM:              0.05,
    unitCost:             220,
    installCost:          120,
    coolingContributionC: 0.60,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["terrace"],
    description:          "UV-rated tensile shade sail. Blocks 85% direct solar radiation.",
  },
  {
    id:                   "vertical_wall_planter",
    name:                 "Vertical Wall Planter Panel 1×1m",
    type:                 "green_wall",
    widthM:               1.0,
    lengthM:              0.15,
    heightM:              1.0,
    unitCost:             95,
    installCost:          40,
    coolingContributionC: 0.20,
    maintenanceLevel:     "moderate",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["balcony", "terrace"],
    description:          "Felt-pocket living wall panel. Holds 12 plants per m².",
  },
  {
    id:                   "container_planter_large",
    name:                 "Large Planter Pot 60cm dia",
    type:                 "planter",
    widthM:               0.6,
    lengthM:              0.6,
    heightM:              0.55,
    unitCost:             65,
    installCost:          5,
    coolingContributionC: 0.12,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace", "balcony"],
    description:          "Frost-resistant fibreglass pot. Suitable for large shrubs.",
  },
  {
    id:                   "container_planter_medium",
    name:                 "Medium Planter Pot 40cm dia",
    type:                 "planter",
    widthM:               0.4,
    lengthM:              0.4,
    heightM:              0.4,
    unitCost:             32,
    installCost:          3,
    coolingContributionC: 0.07,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace", "balcony"],
    description:          "Versatile terracotta-effect pot for perennials and herbs.",
  },
  {
    id:                   "container_planter_small",
    name:                 "Small Planter Pot 25cm dia",
    type:                 "planter",
    widthM:               0.25,
    lengthM:              0.25,
    heightM:              0.25,
    unitCost:             14,
    installCost:          2,
    coolingContributionC: 0.03,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["rooftop", "terrace", "balcony"],
    description:          "Compact pot for herbs, succulents and small annuals.",
  },
  {
    id:                   "rail_planter",
    name:                 "Balcony Rail Planter 60cm",
    type:                 "planter",
    widthM:               0.6,
    lengthM:              0.18,
    heightM:              0.18,
    unitCost:             22,
    installCost:          5,
    coolingContributionC: 0.04,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        1,
    maxFloorLevel:        99,
    compatibleSpaces:     ["balcony"],
    description:          "Galvanised steel rail-clip planter. Fits most standard railings.",
  },
  {
    id:                   "trellis_panel",
    name:                 "Trellis Panel 1.8×0.9m",
    type:                 "trellis",
    widthM:               0.9,
    lengthM:              0.05,
    heightM:              1.8,
    unitCost:             38,
    installCost:          15,
    coolingContributionC: 0.08,
    maintenanceLevel:     "minimal",
    requiresWater:        false,
    requiresStructural:   false,
    minFloorLevel:        0,
    maxFloorLevel:        99,
    compatibleSpaces:     ["balcony", "terrace"],
    description:          "Powder-coated metal trellis for wall mounting. Supports climbers up to 5kg/m.",
  },
];
