// ============================================================
// HeatWise — Plant Library
// recommendation-engine/plants.ts
// ============================================================

import type { Plant } from "@/models";
import { ENGINE_PLANT_ID_TO_CATALOG_CODE } from "@/lib/species/enginePlantCatalogLink";
import type { SpeciesIdentityResolution } from "@/lib/species/speciesIdentityTypes";

function attachSpeciesIdentity(p: Plant): Plant {
  const code = ENGINE_PLANT_ID_TO_CATALOG_CODE[p.id] ?? null;
  const speciesIdentityResolution: SpeciesIdentityResolution =
    code != null ? "canonical_engine_plant" : "unresolved";
  return { ...p, speciesCatalogCode: code, speciesIdentityResolution };
}

const RAW_PLANT_LIBRARY: Plant[] = [
  { id: "sedum_acre", name: "Stonecrop", scientificName: "Sedum acre", type: "succulent", coolingScore: 6, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.2, heightM: 0.05, costPerUnit: 4, coverageSqM: 0.04, notes: "Drought-tolerant ground cover.", placementTip: "Ideal for full-coverage carpet on extensive green roofs." },
  { id: "sedum_reflexum", name: "Reflexed Stonecrop", scientificName: "Sedum reflexum", type: "succulent", coolingScore: 7, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.2, heightM: 0.15, costPerUnit: 5, coverageSqM: 0.04, notes: "Blue-grey foliage.", placementTip: "Mix with S. acre for textural contrast." },
  { id: "sempervivum", name: "Houseleek", scientificName: "Sempervivum tectorum", type: "succulent", coolingScore: 5, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.15, heightM: 0.10, costPerUnit: 3, coverageSqM: 0.02, notes: "Extremely hardy.", placementTip: "Excellent in modular trays." },
  { id: "festuca_glauca", name: "Blue Fescue", scientificName: "Festuca glauca", type: "grass", coolingScore: 7, sunRequirement: ["full"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.3, heightM: 0.30, costPerUnit: 8, coverageSqM: 0.09, notes: "Blue-grey ornamental grass.", placementTip: "Use in groups of 5+." },
  { id: "stipa_tenuissima", name: "Mexican Feather Grass", scientificName: "Stipa tenuissima", type: "grass", coolingScore: 6, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "medium", minSpacingM: 0.3, heightM: 0.60, costPerUnit: 9, coverageSqM: 0.09, notes: "Feathery grass.", placementTip: "Plant in clusters near edges." },
  { id: "pennisetum_alopecuroides", name: "Fountain Grass", scientificName: "Pennisetum alopecuroides", type: "grass", coolingScore: 8, sunRequirement: ["full", "partial"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.5, heightM: 0.80, costPerUnit: 14, coverageSqM: 0.25, notes: "Striking arching habit.", placementTip: "Use as specimen plants." },
  { id: "lavandula", name: "Lavender", scientificName: "Lavandula angustifolia", type: "perennial", coolingScore: 6, sunRequirement: ["full"], maintenance: "minimal", waterNeeds: "low", windTolerance: "medium", minSpacingM: 0.4, heightM: 0.50, costPerUnit: 10, coverageSqM: 0.16, notes: "Fragrant. Pollinator magnet.", placementTip: "Plant on south-facing edges." },
  { id: "armeria_maritima", name: "Sea Thrift", scientificName: "Armeria maritima", type: "perennial", coolingScore: 5, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.2, heightM: 0.20, costPerUnit: 6, coverageSqM: 0.04, notes: "Coastal native.", placementTip: "Ideal for exposed balconies." },
  { id: "echinacea_purpurea", name: "Purple Coneflower", scientificName: "Echinacea purpurea", type: "perennial", coolingScore: 7, sunRequirement: ["full", "partial"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.4, heightM: 0.80, costPerUnit: 12, coverageSqM: 0.16, notes: "Attracts pollinators.", placementTip: "Works well in intensive green roof." },
  { id: "salvia_nemorosa", name: "Balkan Clary Sage", scientificName: "Salvia nemorosa", type: "perennial", coolingScore: 6, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "medium", minSpacingM: 0.35, heightM: 0.45, costPerUnit: 9, coverageSqM: 0.12, notes: "Blue flower spikes.", placementTip: "Plant in drifts." },
  { id: "agapanthus", name: "Lily of the Nile", scientificName: "Agapanthus africanus", type: "perennial", coolingScore: 7, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.5, heightM: 0.70, costPerUnit: 16, coverageSqM: 0.25, notes: "Architectural blue flowers.", placementTip: "Statement pots." },
  { id: "pittosporum_tobira", name: "Japanese Mock Orange", scientificName: "Pittosporum tobira", type: "shrub", coolingScore: 8, sunRequirement: ["full", "partial"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "high", minSpacingM: 0.8, heightM: 1.5, costPerUnit: 28, coverageSqM: 0.64, notes: "Dense evergreen shrub.", placementTip: "Use as privacy screen." },
  { id: "rosmarinus_officinalis", name: "Rosemary", scientificName: "Salvia rosmarinus", type: "shrub", coolingScore: 5, sunRequirement: ["full"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.4, heightM: 0.9, costPerUnit: 12, coverageSqM: 0.16, notes: "Culinary and ornamental.", placementTip: "Plant along south-facing edges." },
  { id: "buxus_sempervirens", name: "Box", scientificName: "Buxus sempervirens", type: "shrub", coolingScore: 6, sunRequirement: ["full", "partial", "shade"], maintenance: "active", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.3, heightM: 1.2, costPerUnit: 18, coverageSqM: 0.09, notes: "Slow-growing evergreen.", placementTip: "Use sparingly for formal structure." },
  { id: "hedera_helix", name: "English Ivy", scientificName: "Hedera helix", type: "climber", coolingScore: 9, sunRequirement: ["partial", "shade"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.5, heightM: 3.0, costPerUnit: 10, coverageSqM: 2.0, notes: "Fast-growing.", placementTip: "Plant at trellis base." },
  { id: "parthenocissus_quinquefolia", name: "Virginia Creeper", scientificName: "Parthenocissus quinquefolia", type: "climber", coolingScore: 10, sunRequirement: ["full", "partial", "shade"], maintenance: "minimal", waterNeeds: "low", windTolerance: "low", minSpacingM: 1.0, heightM: 6.0, costPerUnit: 14, coverageSqM: 5.0, notes: "Highest cooling score.", placementTip: "Best on pergolas." },
  { id: "lonicera_japonica", name: "Japanese Honeysuckle", scientificName: "Lonicera japonica", type: "climber", coolingScore: 8, sunRequirement: ["full", "partial"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.5, heightM: 4.0, costPerUnit: 12, coverageSqM: 3.0, notes: "Fragrant white flowers.", placementTip: "Ideal on pergola frames." },
  { id: "wisteria_sinensis", name: "Chinese Wisteria", scientificName: "Wisteria sinensis", type: "climber", coolingScore: 9, sunRequirement: ["full"], maintenance: "active", waterNeeds: "medium", windTolerance: "low", minSpacingM: 1.5, heightM: 8.0, costPerUnit: 35, coverageSqM: 8.0, notes: "Spectacular flowers.", placementTip: "Premium terraces only." },
  { id: "solanum_lycopersicum", name: "Tomato", scientificName: "Solanum lycopersicum", type: "vegetable", coolingScore: 4, sunRequirement: ["full"], maintenance: "active", waterNeeds: "high", windTolerance: "low", minSpacingM: 0.5, heightM: 1.5, costPerUnit: 4, coverageSqM: 0.25, notes: "High water needs.", placementTip: "Against south-facing wall." },
  { id: "cucurbita_pepo", name: "Courgette / Zucchini", scientificName: "Cucurbita pepo", type: "vegetable", coolingScore: 5, sunRequirement: ["full"], maintenance: "moderate", waterNeeds: "high", windTolerance: "low", minSpacingM: 0.8, heightM: 0.6, costPerUnit: 3, coverageSqM: 0.64, notes: "Large leaf area.", placementTip: "Raised beds only." },
  { id: "phaseolus_coccineus", name: "Runner Bean", scientificName: "Phaseolus coccineus", type: "vegetable", coolingScore: 6, sunRequirement: ["full", "partial"], maintenance: "moderate", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.3, heightM: 2.5, costPerUnit: 2, coverageSqM: 0.5, notes: "Dual-purpose climber.", placementTip: "Plant at trellis base." },
  { id: "polystichum_setiferum", name: "Soft Shield Fern", scientificName: "Polystichum setiferum", type: "fern", coolingScore: 7, sunRequirement: ["shade", "partial"], maintenance: "minimal", waterNeeds: "medium", windTolerance: "low", minSpacingM: 0.5, heightM: 0.7, costPerUnit: 14, coverageSqM: 0.25, notes: "Evergreen.", placementTip: "Group 3–5 in shaded planters." },
  { id: "dryopteris_filix_mas", name: "Male Fern", scientificName: "Dryopteris filix-mas", type: "fern", coolingScore: 8, sunRequirement: ["shade", "partial"], maintenance: "minimal", waterNeeds: "medium", windTolerance: "low", minSpacingM: 0.6, heightM: 1.0, costPerUnit: 16, coverageSqM: 0.36, notes: "Large, architectural fern.", placementTip: "Best in deep containers." },
  { id: "mentha_spicata", name: "Spearmint", scientificName: "Mentha spicata", type: "herb", coolingScore: 4, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "medium", windTolerance: "medium", minSpacingM: 0.25, heightM: 0.40, costPerUnit: 4, coverageSqM: 0.06, notes: "Spreads rapidly.", placementTip: "Containers only." },
  { id: "thymus_serpyllum", name: "Wild Thyme", scientificName: "Thymus serpyllum", type: "herb", coolingScore: 4, sunRequirement: ["full"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.2, heightM: 0.10, costPerUnit: 4, coverageSqM: 0.04, notes: "Mat-forming.", placementTip: "Ground filler in modular trays." },
  { id: "ocimum_basilicum", name: "Basil", scientificName: "Ocimum basilicum", type: "herb", coolingScore: 3, sunRequirement: ["full"], maintenance: "active", waterNeeds: "high", windTolerance: "low", minSpacingM: 0.2, heightM: 0.30, costPerUnit: 3, coverageSqM: 0.04, notes: "Annual.", placementTip: "Sheltered positions only." },
  { id: "allium_schoenoprasum", name: "Chives", scientificName: "Allium schoenoprasum", type: "herb", coolingScore: 3, sunRequirement: ["full", "partial"], maintenance: "minimal", waterNeeds: "low", windTolerance: "high", minSpacingM: 0.15, heightM: 0.30, costPerUnit: 3, coverageSqM: 0.02, notes: "Extremely easy.", placementTip: "Edge rail planters." },
];

export const PLANT_LIBRARY: Plant[] = RAW_PLANT_LIBRARY.map(attachSpeciesIdentity);
