// ============================================================
// HeatWise — Layout Templates Registry
// recommendation-engine/templates.ts
// ============================================================

import type { LayoutTemplate } from "@/models";


export const LAYOUT_TEMPLATES: LayoutTemplate[] = [
  {
    id:                 "intensive_green_roof",
    name:               "Intensive Green Roof",
    type:               "intensive",
    description:        "A full soil-medium green roof with deep substrate supporting a wide variety of plants including shrubs and perennials. Maximum cooling impact.",
    eligibleSpaces:     ["rooftop"],
    eligibleBudgets:    ["high", "premium"],
    eligibleSun:        ["full", "partial"],
    eligibleMaint:      ["moderate", "active"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         30,
    maxAreaSqM:         999,
    minWidthM:          4,
    requiresWater:      true,
    requiresStructural: true,
    moduleIds:          ["irrigation_drip", "substrate_deep", "root_barrier"],
    plantTypes:         ["perennial", "grass", "shrub", "succulent"],
    baseHeatReductionC: 5.0,
    baseCoverageRatio:  0.90,
  },
  {
    id:                 "extensive_sedum_mat",
    name:               "Extensive Sedum Mat",
    type:               "extensive",
    description:        "A low-profile sedum and grass mat system on shallow substrate. Lightweight, low-maintenance, and effective passive cooling.",
    eligibleSpaces:     ["rooftop"],
    eligibleBudgets:    ["low", "medium", "high"],
    eligibleSun:        ["full", "partial"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "mixed"],
    minAreaSqM:         10,
    maxAreaSqM:         999,
    minWidthM:          2,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["substrate_shallow", "root_barrier"],
    plantTypes:         ["succulent", "grass"],
    baseHeatReductionC: 2.8,
    baseCoverageRatio:  0.85,
  },
  {
    id:                 "modular_tray_system",
    name:               "Modular Tray System",
    type:               "modular",
    description:        "Pre-grown plant trays arranged in a grid. Quick to install, easily reconfigured, and suitable for most flat rooftops without structural reinforcement.",
    eligibleSpaces:     ["rooftop", "terrace"],
    eligibleBudgets:    ["medium", "high"],
    eligibleSun:        ["full", "partial", "shade"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         8,
    maxAreaSqM:         999,
    minWidthM:          2,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["modular_tray_60", "irrigation_drip"],
    plantTypes:         ["succulent", "perennial", "herb", "grass"],
    baseHeatReductionC: 3.2,
    baseCoverageRatio:  0.70,
  },
  {
    id:                 "rooftop_food_garden",
    name:               "Rooftop Food Garden",
    type:               "modular",
    description:        "Raised bed system optimised for food production. Combines vegetables and herbs with cooling benefits. Requires active maintenance.",
    eligibleSpaces:     ["rooftop", "terrace"],
    eligibleBudgets:    ["medium", "high", "premium"],
    eligibleSun:        ["full"],
    eligibleMaint:      ["moderate", "active"],
    eligibleGoals:      ["food", "mixed"],
    minAreaSqM:         12,
    maxAreaSqM:         999,
    minWidthM:          3,
    requiresWater:      true,
    requiresStructural: false,
    moduleIds:          ["raised_bed_cedar", "irrigation_drip", "compost_bin"],
    plantTypes:         ["vegetable", "herb", "perennial"],
    baseHeatReductionC: 2.2,
    baseCoverageRatio:  0.60,
  },
  {
    id:                 "pergola_vertical_garden",
    name:               "Pergola + Vertical Garden",
    type:               "vertical",
    description:        "A structural pergola draped with climbing plants, combined with vertical wall planters. Creates a shaded outdoor room with strong cooling effect.",
    eligibleSpaces:     ["terrace"],
    eligibleBudgets:    ["high", "premium"],
    eligibleSun:        ["full", "partial"],
    eligibleMaint:      ["moderate", "active"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         15,
    maxAreaSqM:         999,
    minWidthM:          3,
    requiresWater:      true,
    requiresStructural: true,
    moduleIds:          ["pergola_steel", "vertical_wall_planter", "irrigation_drip"],
    plantTypes:         ["climber", "perennial", "fern"],
    baseHeatReductionC: 4.2,
    baseCoverageRatio:  0.75,
  },
  {
    id:                 "container_garden_shade_sail",
    name:               "Container Garden + Shade Sail",
    type:               "container",
    description:        "Large statement planters grouped with a tensile shade sail structure. Flexible, moveable, and highly effective for medium terraces.",
    eligibleSpaces:     ["terrace"],
    eligibleBudgets:    ["medium", "high"],
    eligibleSun:        ["full", "partial"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         8,
    maxAreaSqM:         100,
    minWidthM:          2.5,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["shade_sail_large", "container_planter_large", "container_planter_medium"],
    plantTypes:         ["shrub", "perennial", "grass"],
    baseHeatReductionC: 2.8,
    baseCoverageRatio:  0.55,
  },
  {
    id:                 "terrace_raised_beds",
    name:               "Terrace Raised Bed Garden",
    type:               "container",
    description:        "Timber raised beds filling the terrace perimeter with a central open space. Good balance of greenery, usability, and low cost.",
    eligibleSpaces:     ["terrace"],
    eligibleBudgets:    ["low", "medium"],
    eligibleSun:        ["full", "partial", "shade"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "food", "aesthetic", "mixed"],
    minAreaSqM:         5,
    maxAreaSqM:         60,
    minWidthM:          2,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["raised_bed_cedar", "raised_bed_small"],
    plantTypes:         ["perennial", "herb", "vegetable", "succulent"],
    baseHeatReductionC: 1.8,
    baseCoverageRatio:  0.45,
  },
  {
    id:                 "trellis_climbers",
    name:               "Trellis + Climbing Plants",
    type:               "vertical",
    description:        "Wall-mounted trellis panels with fast-growing climbers. Maximises green coverage on a vertical plane, ideal for small balconies.",
    eligibleSpaces:     ["balcony", "terrace"],
    eligibleBudgets:    ["low", "medium"],
    eligibleSun:        ["full", "partial", "shade"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         2,
    maxAreaSqM:         40,
    minWidthM:          1.2,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["trellis_panel", "container_planter_small"],
    plantTypes:         ["climber", "fern", "perennial"],
    baseHeatReductionC: 1.6,
    baseCoverageRatio:  0.40,
  },
  {
    id:                 "balcony_rail_planters",
    name:               "Rail Planters + Herb Garden",
    type:               "container",
    description:        "Railing-mounted planters and a compact herb collection on a small shelf system. Best entry-level option for any balcony.",
    eligibleSpaces:     ["balcony"],
    eligibleBudgets:    ["low", "medium", "high"],
    eligibleSun:        ["full", "partial", "shade"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["cooling", "food", "aesthetic", "mixed"],
    minAreaSqM:         1,
    maxAreaSqM:         15,
    minWidthM:          0.8,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["rail_planter", "container_planter_small"],
    plantTypes:         ["herb", "succulent", "perennial"],
    baseHeatReductionC: 0.8,
    baseCoverageRatio:  0.25,
  },
  {
    id:                 "balcony_vertical_wall",
    name:               "Vertical Living Wall",
    type:               "vertical",
    description:        "A panel-based living wall system mounted to the balcony back wall. High visual impact, strong evapotranspiration, compact footprint.",
    eligibleSpaces:     ["balcony"],
    eligibleBudgets:    ["medium", "high", "premium"],
    eligibleSun:        ["partial", "shade"],
    eligibleMaint:      ["moderate", "active"],
    eligibleGoals:      ["cooling", "aesthetic", "mixed"],
    minAreaSqM:         2,
    maxAreaSqM:         30,
    minWidthM:          1.0,
    requiresWater:      true,
    requiresStructural: false,
    moduleIds:          ["vertical_wall_planter", "irrigation_drip"],
    plantTypes:         ["fern", "perennial", "climber", "herb"],
    baseHeatReductionC: 1.4,
    baseCoverageRatio:  0.60,
  },
  {
    id:                 "shade_fern_sanctuary",
    name:               "Shade Fern Sanctuary",
    type:               "container",
    description:        "A curated selection of shade-tolerant ferns and woodland plants in grouped containers. Ideal for north-facing or deeply shaded spaces.",
    eligibleSpaces:     ["rooftop", "terrace", "balcony"],
    eligibleBudgets:    ["low", "medium", "high"],
    eligibleSun:        ["shade", "partial"],
    eligibleMaint:      ["minimal", "moderate"],
    eligibleGoals:      ["aesthetic", "cooling", "mixed"],
    minAreaSqM:         1,
    maxAreaSqM:         999,
    minWidthM:          0.8,
    requiresWater:      false,
    requiresStructural: false,
    moduleIds:          ["container_planter_medium", "container_planter_small"],
    plantTypes:         ["fern", "perennial"],
    baseHeatReductionC: 0.9,
    baseCoverageRatio:  0.35,
  },
];
