"""
Resolve display / ML species labels to ``SpeciesCatalog.code`` (canonical id).

Uses the shared artifact ``data/species/species_catalog_mapping.v1.json`` (Phase 11),
generated by ``scripts/generate-species-catalog-mapping.mjs`` from seed + extensions.

Override path with env ``HEATWISE_SPECIES_MAPPING_JSON``.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

_ARTIFACT_FILENAME = "species_catalog_mapping.v1.json"


def _artifact_path() -> Path:
    override = os.environ.get("HEATWISE_SPECIES_MAPPING_JSON", "").strip()
    if override:
        return Path(override)
    # heatwise/ml/serving/species/catalog_code_resolve.py -> parents[3] == heatwise app root
    repo_root = Path(__file__).resolve().parents[3]
    return repo_root / "data" / "species" / _ARTIFACT_FILENAME


def _load_mapping() -> tuple[dict[str, str], frozenset[str]]:
    path = _artifact_path()
    if not path.is_file():
        raise FileNotFoundError(
            f"Species catalog mapping artifact missing: {path}\n"
            "  Fix: from heatwise repo root, run `npm run gen:species-mapping`, "
            "commit data/species/species_catalog_mapping.v1.json, and ship it with the serving bundle.\n"
            "  Optional: set HEATWISE_SPECIES_MAPPING_JSON to a full path to the JSON file.\n"
            "  CI: `npm run check:species-mapping` catches stale or missing artifacts.",
        )
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Species mapping artifact is not a JSON object: {path}")
    alias = dict(data.get("aliasToCode") or {})
    codes_list = data.get("canonicalCodes") or []
    codes = frozenset(str(c) for c in codes_list if c)
    if not codes:
        raise ValueError(
            f"Species mapping artifact has no canonicalCodes: {path}. Regenerate with npm run gen:species-mapping.",
        )
    if not alias:
        raise ValueError(
            f"Species mapping artifact has no aliasToCode: {path}. Regenerate with npm run gen:species-mapping.",
        )
    return alias, codes


SPECIES_LABEL_TO_CATALOG_CODE, CANONICAL_SPECIES_CODES = _load_mapping()


def normalize_species_alias_key(raw: str) -> str:
    s = raw.strip().lower()
    s = re.sub(r"[_/]+", " ", s)
    s = re.sub(r"\s+", " ", s)
    s = s.replace(".", "")
    return s.strip()


def _lookup_alias(normalized: str) -> str | None:
    if not normalized:
        return None
    direct = SPECIES_LABEL_TO_CATALOG_CODE.get(normalized)
    if direct is not None:
        return direct
    collapsed = normalized.replace(" ", "")
    for k, code in SPECIES_LABEL_TO_CATALOG_CODE.items():
        if k.replace(" ", "") == collapsed:
            return code
    return None


def resolve_catalog_code_from_ml_or_display_label(raw_label: str) -> str | None:
    """
    Return a canonical ``SpeciesCatalog.code`` when the label maps cleanly; otherwise None.
    Never guesses or invents codes for unknown taxa.
    """
    trimmed = raw_label.strip()
    if not trimmed:
        return None

    norm = normalize_species_alias_key(trimmed)
    if not norm:
        return None

    snake = norm.replace(" ", "_")
    if snake in CANONICAL_SPECIES_CODES:
        return snake

    via_alias = _lookup_alias(norm)
    if via_alias is not None:
        return via_alias

    if snake in SPECIES_LABEL_TO_CATALOG_CODE:
        return SPECIES_LABEL_TO_CATALOG_CODE[snake]

    return None


def attach_species_catalog_code_to_candidate_payload(cand: dict[str, Any]) -> None:
    """Mutates ``cand``: sets or removes ``species_catalog_code``."""
    raw = cand.get("species_primary")
    text = str(raw).strip() if raw is not None else ""
    code = resolve_catalog_code_from_ml_or_display_label(text)
    if code:
        cand["species_catalog_code"] = code
    else:
        cand.pop("species_catalog_code", None)


def enrich_ranked_rows_catalog_identity(scored_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    After supply/geo mutations to ``species_primary``, attach canonical codes for telemetry/Node.
    """
    for row in scored_rows:
        payload = row.get("candidatePayload")
        if isinstance(payload, dict):
            attach_species_catalog_code_to_candidate_payload(payload)
            row["candidatePayload"] = payload
    return scored_rows


__all__ = [
    "CANONICAL_SPECIES_CODES",
    "SPECIES_LABEL_TO_CATALOG_CODE",
    "attach_species_catalog_code_to_candidate_payload",
    "enrich_ranked_rows_catalog_identity",
    "normalize_species_alias_key",
    "resolve_catalog_code_from_ml_or_display_label",
]
