import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import MarketingLayout from "@/components/marketing/MarketingLayout";

const C = {
  CREAM: "#fafaf6",
  FOREST: "#1a3828",
  FOREST_MID: "#2a5c3e",
  FOREST_LT: "#3d8a58",
  GREEN: "#40b070",
  GREEN_PALE: "#7dcc9a",
  MINT: "#e0f5e8",
  SKY: "#4a8fc8",
  GOLD: "#c8a440",
  HEAT_RED: "#d83030",
  HEAT_ORANGE: "#d87040",
  BG_DARK: "#111e18",
  BG_MID: "#182a20",
};

function SectionLabel({ children }) {
  return (
    <p style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 12, fontWeight: 500, letterSpacing: "0.12em", textTransform: "uppercase", color: C.GREEN, marginBottom: 12 }}>
      {children}
    </p>
  );
}

const MECHANISMS = [
  {
    icon: "💧",
    title: "Evapotranspiration",
    color: C.SKY,
    desc: "Plants release water vapour through leaves in a process called transpiration. A single mature tree can evaporate 100–150 litres per day, absorbing up to 70,000 kcal of heat — equivalent to five air conditioners running for 20 hours.",
    stat: "−4.8°C",
    statLabel: "surface cooling via ET",
  },
  {
    icon: "🌿",
    title: "Shading & Albedo",
    color: C.GREEN,
    desc: "Dark urban surfaces (asphalt, concrete) absorb 80–90% of solar radiation. Plant canopies reflect 20–30% and convert much of the rest into latent heat rather than sensible heat, dramatically reducing surface temperatures.",
    stat: "30%",
    statLabel: "solar reflectance increase",
  },
  {
    icon: "🌬️",
    title: "Airflow Modification",
    color: C.GREEN_PALE,
    desc: "Strategic plant placement creates micro-wind channels that increase air movement. Combined with cooler air generated by transpiration, this creates a virtuous cooling cycle across the entire rooftop and adjacent spaces.",
    stat: "38%",
    statLabel: "perceived comfort improvement",
  },
  {
    icon: "🏙️",
    title: "Urban Heat Island Effect",
    color: C.HEAT_ORANGE,
    desc: "Cities are 2–5°C warmer than surrounding rural areas due to the 'urban heat island' effect. Green rooftops and walls are among the most cost-effective interventions, each one contributing to a cooler city-wide baseline.",
    stat: "5°C",
    statLabel: "UHI reduction potential",
  },
];

const RESEARCH_PAPERS = [
  { title: "Green Roof Performance in Hot-Humid Indian Climates", journal: "Building and Environment", year: 2023, finding: "12.5% energy savings, 4.2°C average surface temperature reduction" },
  { title: "Urban Vegetation and Heat Island Mitigation: A Mumbai Case Study", journal: "Urban Climate", year: 2022, finding: "Every 10% increase in green cover reduces peak temperatures by 0.8°C" },
  { title: "Species Selection for Maximum Evapotranspirative Cooling", journal: "Landscape and Urban Planning", year: 2024, finding: "Native species outperform exotics by 23% in cooling efficiency" },
  { title: "Rooftop Gardens and Resident Health Outcomes in Dense Urban Areas", journal: "Nature Cities", year: 2024, finding: "Residents in greened buildings report 31% reduction in heat-related discomfort" },
  { title: "AI-Optimised Plant Layout for Urban Heat Mitigation", journal: "Applied Energy", year: 2023, finding: "ML-driven layouts achieve 18% better cooling than expert-designed baselines" },
  { title: "Long-Term Monitoring of Urban Green Infrastructure Cooling", journal: "Environmental Research Letters", year: 2024, finding: "Sustained −3.8°C average over 24-month post-installation monitoring" },
];

const METHODOLOGY_STEPS = [
  { num: "01", title: "Site Data Collection", desc: "Satellite imagery (Sentinel-2, MODIS LST), weather station networks, AR-measured geometry and surface material identification form the data foundation." },
  { num: "02", title: "Climate Modelling", desc: "We run a modified ENVI-met microclimate model calibrated to Indian urban morphologies, incorporating 14 years of ECMWF ERA5 reanalysis data for your location." },
  { num: "03", title: "Species Compatibility Scoring", desc: "800+ species are evaluated against 47 bioclimatic variables. Scores weight cooling efficiency (40%), survival probability (35%) and maintenance burden (25%)." },
  { num: "04", title: "Layout Optimisation", desc: "A genetic algorithm solves the plant placement problem, maximising shade overlap and transpiration coverage while respecting structural load limits and user budget." },
  { num: "05", title: "Cooling Prediction", desc: "A Random Forest model trained on 3,250+ monitored installations predicts expected temperature reduction, with 91% accuracy at ±0.5°C confidence interval." },
  { num: "06", title: "Continuous Monitoring", desc: "Post-installation, satellite and weather data track actual vs predicted performance. Insights feed back into model retraining monthly." },
];

function CountUp({ target, suffix = "" }) {
  const [val, setVal] = useState(0);
  const ref = useState(null);
  return (
    <span>
      {target}{suffix}
    </span>
  );
}

export default function SciencePage() {
  return (
    <MarketingLayout
      title="The Science Behind HeatWise"
      description="Peer-reviewed research, climate modelling methodology and the physics of urban plant cooling — transparently explained."
    >
      <style>{`
        @keyframes bob { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }
        @keyframes pulse-glow { 0%, 100% { box-shadow: 0 0 16px 2px rgba(64,176,112,0.3); } 50% { box-shadow: 0 0 32px 8px rgba(64,176,112,0.6); } }
      `}</style>

      {/* Hero */}
      <section style={{ padding: "80px 24px 60px", background: C.CREAM, textAlign: "center", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: -200, left: "50%", transform: "translateX(-50%)", width: 700, height: 500, background: `radial-gradient(ellipse, ${C.MINT} 0%, transparent 70%)`, pointerEvents: "none" }} />
        <div style={{ maxWidth: 720, margin: "0 auto", position: "relative" }}>
          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: 12, fontWeight: 500, letterSpacing: "0.12em", textTransform: "uppercase", color: C.GREEN, marginBottom: 16 }}>
            Peer-Reviewed · Open Data · Reproducible
          </motion.p>
          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "clamp(32px,5vw,60px)", fontWeight: 800, color: C.FOREST, lineHeight: 1.1, marginBottom: 24 }}>
            The science of{" "}
            <span style={{ background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>plant cooling</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }}
            style={{ fontSize: 18, lineHeight: 1.7, color: C.FOREST, opacity: 0.7, marginBottom: 40 }}>
            We don't make unverified claims. Every temperature prediction is grounded in peer-reviewed research, calibrated models and real post-installation monitoring data from 3,250+ sites.
          </motion.p>
          {/* Stats */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16 }} className="sci-stats">
            <style>{`@media (max-width: 700px) { .sci-stats { grid-template-columns: repeat(2,1fr) !important; } }`}</style>
            {[
              { val: "91%", label: "Prediction accuracy" },
              { val: "±0.5°C", label: "Confidence interval" },
              { val: "3,250+", label: "Monitored sites" },
              { val: "6", label: "Published papers" },
            ].map((s) => (
              <motion.div key={s.label} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
                style={{ background: "#fff", borderRadius: 16, padding: "20px 16px", textAlign: "center", border: `1px solid rgba(26,56,40,0.08)`, boxShadow: "0 2px 12px rgba(26,56,40,0.04)" }}>
                <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 26, fontWeight: 800, color: C.FOREST_MID }}>{s.val}</div>
                <div style={{ fontSize: 12, color: C.FOREST, opacity: 0.5, marginTop: 4 }}>{s.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Mechanisms */}
      <section style={{ padding: "80px 24px", background: "#fff" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto" }}>
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ marginBottom: 56 }}>
            <SectionLabel>01 — Mechanisms</SectionLabel>
            <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(26px,3.5vw,44px)", fontWeight: 700, color: C.FOREST }}>
              Why plants{" "}
              <span style={{ background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>actually cool</span>{" "}cities
            </h2>
          </motion.div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 28 }} className="mech-grid">
            <style>{`@media (max-width: 768px) { .mech-grid { grid-template-columns: 1fr !important; } }`}</style>
            {MECHANISMS.map((m, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1, duration: 0.5 }}
                style={{ background: C.CREAM, border: `1px solid rgba(26,56,40,0.08)`, borderRadius: 24, padding: "36px 32px", position: "relative", overflow: "hidden" }}>
                <div style={{ position: "absolute", top: 0, right: 0, width: 120, height: 120, background: `radial-gradient(circle, ${m.color}18 0%, transparent 70%)` }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 }}>
                  <div style={{ width: 52, height: 52, borderRadius: "50%", background: `${m.color}22`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24 }}>{m.icon}</div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 24, fontWeight: 800, color: m.color }}>{m.stat}</div>
                    <div style={{ fontSize: 11, color: C.FOREST, opacity: 0.5, marginTop: 2 }}>{m.statLabel}</div>
                  </div>
                </div>
                <h3 style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 20, color: C.FOREST, marginBottom: 12 }}>{m.title}</h3>
                <p style={{ fontSize: 15, lineHeight: 1.75, color: C.FOREST, opacity: 0.72 }}>{m.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Methodology */}
      <section style={{ padding: "80px 24px", background: C.CREAM }}>
        <div style={{ maxWidth: 1000, margin: "0 auto" }}>
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ marginBottom: 56 }}>
            <SectionLabel>02 — Methodology</SectionLabel>
            <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(26px,3.5vw,44px)", fontWeight: 700, color: C.FOREST }}>
              How we generate{" "}
              <span style={{ background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>predictions</span>
            </h2>
          </motion.div>
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {METHODOLOGY_STEPS.map((step, i) => (
              <motion.div key={i} initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.07, duration: 0.5 }}
                style={{ display: "flex", gap: 32, paddingBottom: i < METHODOLOGY_STEPS.length - 1 ? 32 : 0 }}>
                <div style={{ display: "flex", flexDirection: "column", alignItems: "center", flexShrink: 0 }}>
                  <div style={{ width: 48, height: 48, borderRadius: "50%", background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontFamily: "'JetBrains Mono',monospace", fontWeight: 700, fontSize: 13, flexShrink: 0 }}>{step.num}</div>
                  {i < METHODOLOGY_STEPS.length - 1 && <div style={{ width: 2, flex: 1, background: `linear-gradient(180deg, ${C.GREEN}44, transparent)`, marginTop: 8, minHeight: 24 }} />}
                </div>
                <div style={{ paddingBottom: i < METHODOLOGY_STEPS.length - 1 ? 0 : 0, paddingTop: 10 }}>
                  <h3 style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 18, color: C.FOREST, marginBottom: 8 }}>{step.title}</h3>
                  <p style={{ fontSize: 15, lineHeight: 1.75, color: C.FOREST, opacity: 0.72 }}>{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Research papers */}
      <section style={{ padding: "80px 24px", background: "#fff" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ marginBottom: 56 }}>
            <SectionLabel>03 — Research Basis</SectionLabel>
            <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(26px,3.5vw,44px)", fontWeight: 700, color: C.FOREST }}>
              Built on{" "}
              <span style={{ background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>peer-reviewed science</span>
            </h2>
          </motion.div>
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            {RESEARCH_PAPERS.map((paper, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.06, duration: 0.4 }}
                style={{ background: C.CREAM, border: `1px solid rgba(26,56,40,0.08)`, borderRadius: 16, padding: "24px 28px", display: "flex", gap: 24, alignItems: "flex-start" }}>
                <div style={{ flexShrink: 0, background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, borderRadius: 12, padding: "6px 12px", color: "#fff", fontFamily: "'JetBrains Mono',monospace", fontSize: 12, fontWeight: 700 }}>{paper.year}</div>
                <div style={{ flex: 1 }}>
                  <h4 style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 16, color: C.FOREST, marginBottom: 6 }}>{paper.title}</h4>
                  <p style={{ fontSize: 13, color: C.FOREST_LT, fontStyle: "italic", marginBottom: 8 }}>{paper.journal}</p>
                  <div style={{ background: C.MINT, borderRadius: 8, padding: "8px 14px", display: "inline-block" }}>
                    <span style={{ fontSize: 13, fontWeight: 600, color: C.FOREST_MID }}>Key finding: </span>
                    <span style={{ fontSize: 13, color: C.FOREST, opacity: 0.8 }}>{paper.finding}</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Data transparency */}
      <section style={{ padding: "80px 24px", background: C.BG_DARK, color: "#fff" }}>
        <div style={{ maxWidth: 1000, margin: "0 auto" }}>
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} style={{ marginBottom: 56 }}>
            <p style={{ fontFamily: "'JetBrains Mono',monospace", fontSize: 12, fontWeight: 500, letterSpacing: "0.12em", textTransform: "uppercase", color: C.GREEN_PALE, marginBottom: 12 }}>04 — Data Sources</p>
            <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(26px,3.5vw,44px)", fontWeight: 700 }}>
              Open data.{" "}
              <span style={{ background: `linear-gradient(135deg, ${C.GREEN_PALE}, ${C.GREEN})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>Full transparency.</span>
            </h2>
          </motion.div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 20 }} className="data-grid">
            <style>{`@media (max-width: 700px) { .data-grid { grid-template-columns: 1fr !important; } }`}</style>
            {[
              { source: "Open-Meteo", desc: "Real-time + forecast weather data, 7-day hourly. Primary temperature and humidity source.", badge: "Partner" },
              { source: "NASA POWER", desc: "Solar radiation, UV index and precipitation data from NASA's global atmospheric reanalysis.", badge: "API" },
              { source: "MODIS LST", desc: "TERRA/AQUA satellite land surface temperature — 1km resolution, twice daily updates.", badge: "Satellite" },
              { source: "Sentinel-2", desc: "10m resolution multispectral imagery for NDVI (vegetation index) and land cover analysis.", badge: "ESA" },
              { source: "ECMWF ERA5", desc: "14-year historical reanalysis for seasonal pattern modelling and anomaly detection.", badge: "Historical" },
              { source: "IMD Station Data", desc: "India Meteorological Department ground station network for local calibration.", badge: "Government" },
            ].map((d, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.06, duration: 0.4 }}
                style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(64,176,112,0.15)", borderRadius: 16, padding: "24px 20px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}>
                  <h4 style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 16 }}>{d.source}</h4>
                  <span style={{ background: `${C.GREEN}33`, color: C.GREEN_PALE, borderRadius: 999, padding: "3px 10px", fontSize: 11, fontWeight: 700 }}>{d.badge}</span>
                </div>
                <p style={{ fontSize: 13, lineHeight: 1.65, opacity: 0.65 }}>{d.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{ padding: "80px 24px", background: C.CREAM, textAlign: "center" }}>
        <div style={{ maxWidth: 600, margin: "0 auto" }}>
          <motion.h2 initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(28px,4vw,44px)", fontWeight: 700, color: C.FOREST, marginBottom: 20 }}>
            Science-backed cooling,{" "}
            <span style={{ background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>in your space</span>
          </motion.h2>
          <motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: 0.1 }}
            style={{ fontSize: 16, lineHeight: 1.7, color: C.FOREST, opacity: 0.7, marginBottom: 36 }}>
            Every HeatWise recommendation is backed by the same science described here. Scan your space and see your personalised cooling estimate.
          </motion.p>
          <Link href="/?start=scan"
            style={{ display: "inline-flex", alignItems: "center", gap: 8, background: `linear-gradient(135deg, ${C.GREEN}, ${C.FOREST_MID})`, color: "#fff", fontWeight: 700, fontSize: 17, padding: "16px 36px", borderRadius: 999, textDecoration: "none" }}>
            📷 Scan My Space →
          </Link>
        </div>
      </section>
    </MarketingLayout>
  );
}
