#!/usr/bin/env python3
"""
HeatWise Species Recommender — Rule-Based ML Training
======================================================
Trains three complementary models from the rule-based species catalog:

  1. species_scorer    — GBT regressor predicting species relevance score (0–1)
                         given scenario context (sun, water, wind, purpose, etc.)
  2. species_ranker    — GBT pairwise ranker distinguishing good vs bad fit
                         for a given scenario (binary preference label)
  3. heat_scorer       — GBT regressor predicting cooling contribution score
                         from species traits + scenario heat context

Synthetic training data is generated by applying the rule-based scoring formulas
directly to every (scenario, species) combination. The models learn to generalise
these rules to unseen species/scenario combinations and can be blended with the
TypeScript catalog-hybrid fallback.

Usage
-----
  python training/train_species_recommender.py \\
      --species-csv data/bootstrap/sample_outputs/demo_pack/species_features.csv \\
      --out-dir registry/artifacts \\
      --registry-dir registry \\
      [--n-scenarios 4000] [--seed 42]

Output
------
  registry/artifacts/species_scorer/     model.joblib + metadata.json
  registry/artifacts/species_ranker/     model.joblib + metadata.json
  registry/artifacts/heat_scorer/        model.joblib + metadata.json
  registry/registry_index.json           updated with all 3 entries
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    roc_auc_score,
    accuracy_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings("ignore", category=FutureWarning)

# ─────────────────────────────────────────────────────────────────────────────
# 1. Species feature loading and encoding
# ─────────────────────────────────────────────────────────────────────────────

CLIMATE_ORDER = ["HOT_HUMID", "HOT_DRY", "MONSOON_HEAVY", "TEMPERATE_LITE"]
WATER_ORDER   = {"LOW": 0, "MED": 1, "HIGH": 2}
SUN_ORDER     = {"SHADE": 0, "PART": 1, "FULL": 2}
MAINT_ORDER   = {"LOW": 0, "MED": 1, "HIGH": 2}
ROOT_ORDER    = {"LOW": 0, "MED": 1, "HIGH": 2}
SAFETY_ORDER  = {"SAFE": 2, "CAUTION": 1, "UNSAFE": 0}
NATIVE_ORDER  = {"LOW": 0, "MED": 1, "HIGH": 2}
CONT_ORDER    = {"EXCELLENT": 3, "GOOD": 2, "FAIR": 1, "POOR": 0}


def load_species(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)

    # Expand pipe-separated climate_suitability → one-hot per climate
    for c in CLIMATE_ORDER:
        df[f"climate_{c.lower()}"] = df["climate_suitability"].str.contains(c, na=False).astype(int)

    # Ordinal encode
    df["water_demand_ord"]         = df["water_demand"].map(WATER_ORDER).fillna(1).astype(int)
    df["sunlight_pref_ord"]        = df["sunlight_preference"].map(SUN_ORDER).fillna(1).astype(int)
    df["maintenance_ord"]          = df["maintenance_need"].map(MAINT_ORDER).fillna(1).astype(int)
    df["root_aggressiveness_ord"]  = df["root_aggressiveness"].map(ROOT_ORDER).fillna(1).astype(int)
    df["child_pet_safety_ord"]     = df["child_pet_safety"].map(SAFETY_ORDER).fillna(1).astype(int)
    df["native_support_ord"]       = df["native_support"].map(NATIVE_ORDER).fillna(1).astype(int)
    df["container_suitability_ord"]= df["container_suitability"].map(CONT_ORDER).fillna(2).astype(int)

    # Growth-habit one-hot
    habits = ["HERB", "SHRUB", "UPRIGHT", "VINE", "GROUND_COVER",
              "TRAILING", "SUCCULENT", "GRASS"]
    for h in habits:
        df[f"habit_{h.lower()}"] = (df["growth_habit"] == h).astype(int)

    # Cast numeric columns
    for col in ["pollinator_value", "cooling_contribution", "privacy_contribution",
                "edible"]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(float)

    return df


SPECIES_FEATURE_COLS = [
    # Climate match
    "climate_hot_humid", "climate_hot_dry", "climate_monsoon_heavy", "climate_temperate_lite",
    # Light, water, maintenance
    "sunlight_pref_ord", "water_demand_ord", "maintenance_ord",
    # Safety, nativeness, container fit
    "child_pet_safety_ord", "native_support_ord", "container_suitability_ord",
    "root_aggressiveness_ord",
    # Ecological values
    "pollinator_value", "cooling_contribution", "privacy_contribution", "edible",
    # Growth habit
    "habit_herb", "habit_shrub", "habit_upright", "habit_vine",
    "habit_ground_cover", "habit_trailing", "habit_succulent", "habit_grass",
]


# ─────────────────────────────────────────────────────────────────────────────
# 2. Scenario generation  (rich synthetic variety)
# ─────────────────────────────────────────────────────────────────────────────

PURPOSES   = ["cooling", "food", "aesthetic", "privacy", "biodiversity", "mixed"]
SUN_LEVELS = ["full", "partial", "shade"]
WATER_AVAIL= ["scarce", "moderate", "plentiful"]
WIND_LEVELS= ["low", "medium", "high"]
SPACE_TYPES= ["outdoor_rooftop", "outdoor_balcony", "outdoor_terrace", "indoor"]
MAINT_PREF = ["minimal", "low", "moderate", "high"]

def generate_scenarios(n: int, rng: random.Random) -> list[dict]:
    scenarios = []
    for _ in range(n):
        sun   = rng.choice(SUN_LEVELS)
        water = rng.choice(WATER_AVAIL)
        wind  = rng.choice(WIND_LEVELS)
        space = rng.choice(SPACE_TYPES)
        purp  = rng.choice(PURPOSES)
        maint = rng.choice(MAINT_PREF)
        pet   = rng.random() < 0.35    # 35 % pet/child-safe required
        edible= rng.random() < 0.30    # 30 % edible preferred
        floor = rng.randint(1, 25)
        area  = rng.uniform(4, 80)
        heat  = rng.choice(["low", "moderate", "high", "extreme"])

        scenarios.append({
            "sun": sun,
            "water_availability": water,
            "wind_level": wind,
            "space_type": space,
            "purpose_primary": purp,
            "maintenance_preference": maint,
            "pet_safe_required": int(pet),
            "edible_preferred": int(edible),
            "floor_level": floor,
            "area_m2": round(area, 1),
            "heat_exposure": heat,
        })
    return scenarios


# ─────────────────────────────────────────────────────────────────────────────
# 3. Rule-based scoring  (mirrors TypeScript catalogHybridFallback logic)
# ─────────────────────────────────────────────────────────────────────────────

def _sun_match(sp_sun_ord: int, scenario_sun: str) -> float:
    """How well does the species sun preference match the scenario?"""
    sc = {"shade": 0, "partial": 1, "full": 2}[scenario_sun]
    diff = abs(sp_sun_ord - sc)
    return max(0.0, 1.0 - diff * 0.45)


def _water_match(sp_water_ord: int, water_avail: str) -> float:
    sc = {"scarce": 0, "moderate": 1, "plentiful": 2}[water_avail]
    # High water demand under scarce = hard penalise
    if sp_water_ord == 2 and water_avail == "scarce":
        return 0.1
    diff = abs(sp_water_ord - sc)
    return max(0.0, 1.0 - diff * 0.35)


def _wind_match(root_ord: int, habit: str, wind_level: str) -> float:
    wsc = {"low": 0, "medium": 1, "high": 2}[wind_level]
    # Vines and tall grasses penalised on high wind
    fragile = int(habit in ("VINE", "GRASS", "UPRIGHT")) * 0.3
    base = max(0.0, 1.0 - (wsc * fragile))
    # Deep-rooted (HIGH root aggressiveness) helps in wind
    base += root_ord * 0.07 * wsc
    return min(1.0, base)


def _purpose_score(sp: dict, purpose: str) -> float:
    score = 0.5
    cc  = float(sp.get("cooling_contribution", 0))
    prv = float(sp.get("privacy_contribution", 0))
    pol = float(sp.get("pollinator_value", 0))
    edible = float(sp.get("edible", 0))

    if purpose == "cooling":
        score = 0.3 + cc / 3.0 * 0.7
    elif purpose == "food":
        score = 0.2 + edible * 0.6 + pol / 3.0 * 0.2
    elif purpose == "aesthetic":
        score = 0.3 + pol / 3.0 * 0.5 + cc / 3.0 * 0.2
    elif purpose == "privacy":
        score = 0.3 + prv / 3.0 * 0.7
    elif purpose == "biodiversity":
        score = 0.3 + pol / 3.0 * 0.5 + edible * 0.2
    elif purpose == "mixed":
        score = 0.35 + (cc + prv + pol) / 9.0 * 0.65
    return float(np.clip(score, 0.0, 1.0))


def _maintenance_match(sp_maint_ord: int, pref: str) -> float:
    pref_ord = {"minimal": 0, "low": 0, "moderate": 1, "high": 2}[pref]
    # User wants minimal: low-maintenance species are better
    if pref_ord == 0:
        return max(0.0, 1.0 - sp_maint_ord * 0.45)
    return max(0.0, 1.0 - abs(sp_maint_ord - pref_ord) * 0.25)


def _pet_safe_score(safety_ord: int, required: int) -> float:
    if required and safety_ord == 0:  # UNSAFE and required safe
        return 0.0  # hard block → model learns zero score
    if required:
        return float(safety_ord) / 2.0  # SAFE=1.0, CAUTION=0.5
    return 0.7  # not required → neutral


def _heat_score(sp: dict, heat_exposure: str) -> float:
    """Cooling contribution weighted by scenario heat severity."""
    cc  = float(sp.get("cooling_contribution", 0))
    hot = int(sp.get("climate_hot_dry", 0) or sp.get("climate_hot_humid", 0))
    heat_w = {"low": 0.3, "moderate": 0.6, "high": 0.85, "extreme": 1.0}[heat_exposure]
    base = cc / 3.0 * heat_w + hot * 0.1 * heat_w
    return float(np.clip(base, 0.0, 1.0))


def rule_score(sp: pd.Series, scenario: dict) -> tuple[float, float]:
    """
    Returns (relevance_score, heat_score) in [0, 1].
    Mirrors the TypeScript catalogHybridFallback scoring weights.
    """
    spd = sp.to_dict()
    sun_m  = _sun_match(int(spd["sunlight_pref_ord"]), scenario["sun"])
    water_m= _water_match(int(spd["water_demand_ord"]), scenario["water_availability"])
    wind_m = _wind_match(int(spd["root_aggressiveness_ord"]),
                         str(spd.get("growth_habit", "HERB")),
                         scenario["wind_level"])
    purp_m = _purpose_score(spd, scenario["purpose_primary"])
    maint_m= _maintenance_match(int(spd["maintenance_ord"]), scenario["maintenance_preference"])
    pet_m  = _pet_safe_score(int(spd["child_pet_safety_ord"]), scenario["pet_safe_required"])
    heat_m = _heat_score(spd, scenario["heat_exposure"])

    # Floor-level penalty: high-floor + high-maintenance + high-water = stress
    floor_pen = max(0.0, (scenario["floor_level"] - 8) / 25.0) * (
        int(spd["water_demand_ord"]) + int(spd["maintenance_ord"])
    ) * 0.04

    # Container bonus for small spaces / balconies
    cont_bonus = 0.0
    if scenario["space_type"] in ("outdoor_balcony", "indoor"):
        cont_bonus = (int(spd["container_suitability_ord"]) - 1) * 0.04

    # Weighted relevance
    relevance = (
        sun_m   * 0.25 +
        water_m * 0.22 +
        purp_m  * 0.20 +
        maint_m * 0.12 +
        pet_m   * 0.10 +
        wind_m  * 0.06 +
        cont_bonus
        - floor_pen
    )
    relevance = float(np.clip(relevance, 0.0, 1.0))
    return relevance, heat_m


# ─────────────────────────────────────────────────────────────────────────────
# 4. Build training datasets
# ─────────────────────────────────────────────────────────────────────────────

SCENARIO_FEATURE_COLS = [
    "sun_ord", "water_avail_ord", "wind_ord", "heat_ord",
    "purpose_cooling", "purpose_food", "purpose_aesthetic",
    "purpose_privacy", "purpose_biodiversity", "purpose_mixed",
    "maint_pref_ord", "pet_safe_required", "edible_preferred",
    "floor_level_norm", "area_m2_norm",
    "space_balcony", "space_indoor", "space_rooftop", "space_terrace",
]

def encode_scenario(sc: dict) -> dict:
    sun_ord   = {"shade": 0, "partial": 1, "full": 2}[sc["sun"]]
    water_ord = {"scarce": 0, "moderate": 1, "plentiful": 2}[sc["water_availability"]]
    wind_ord  = {"low": 0, "medium": 1, "high": 2}[sc["wind_level"]]
    heat_ord  = {"low": 0, "moderate": 1, "high": 2, "extreme": 3}[sc["heat_exposure"]]
    maint_ord = {"minimal": 0, "low": 0, "moderate": 1, "high": 2}[sc["maintenance_preference"]]
    purp = sc["purpose_primary"]
    return {
        "sun_ord":          sun_ord,
        "water_avail_ord":  water_ord,
        "wind_ord":         wind_ord,
        "heat_ord":         heat_ord,
        "maint_pref_ord":   maint_ord,
        "pet_safe_required":sc["pet_safe_required"],
        "edible_preferred": sc["edible_preferred"],
        "floor_level_norm": min(1.0, sc["floor_level"] / 25.0),
        "area_m2_norm":     min(1.0, sc["area_m2"] / 80.0),
        "purpose_cooling":    int(purp == "cooling"),
        "purpose_food":       int(purp == "food"),
        "purpose_aesthetic":  int(purp == "aesthetic"),
        "purpose_privacy":    int(purp == "privacy"),
        "purpose_biodiversity": int(purp == "biodiversity"),
        "purpose_mixed":      int(purp == "mixed"),
        "space_balcony":  int(sc["space_type"] == "outdoor_balcony"),
        "space_indoor":   int(sc["space_type"] == "indoor"),
        "space_rooftop":  int(sc["space_type"] == "outdoor_rooftop"),
        "space_terrace":  int(sc["space_type"] == "outdoor_terrace"),
    }


def build_regression_dataset(
    species_df: pd.DataFrame,
    scenarios: list[dict],
) -> tuple[pd.DataFrame, np.ndarray, np.ndarray]:
    """Cross-product of scenarios × species, returns X, y_relevance, y_heat."""
    rows, y_rel, y_heat = [], [], []
    for sc in scenarios:
        sc_feat = encode_scenario(sc)
        for _, sp in species_df.iterrows():
            rel, ht = rule_score(sp, sc)
            row = {**sc_feat}
            for col in SPECIES_FEATURE_COLS:
                row[col] = float(sp[col])
            rows.append(row)
            y_rel.append(rel)
            y_heat.append(ht)

    X = pd.DataFrame(rows)
    return X, np.array(y_rel, dtype=np.float32), np.array(y_heat, dtype=np.float32)


def build_pairwise_dataset(
    species_df: pd.DataFrame,
    scenarios: list[dict],
    rng: random.Random,
    pairs_per_scenario: int = 6,
) -> tuple[pd.DataFrame, np.ndarray]:
    """
    For each scenario, sample pairs (spA, spB) where spA has higher rule score.
    Label = 1 if spA features are presented as 'preferred'.
    Features = [scenario, spA_features, spB_features] — diff-encoding.
    """
    rows, labels = [], []
    n_sp = len(species_df)
    sp_list = species_df.reset_index(drop=True)

    for sc in scenarios:
        sc_feat = encode_scenario(sc)
        # Pre-compute scores for all species in this scenario
        scores = []
        for _, sp in sp_list.iterrows():
            r, _ = rule_score(sp, sc)
            scores.append(r)
        scores = np.array(scores)

        for _ in range(pairs_per_scenario):
            ia, ib = rng.sample(range(n_sp), 2)
            ra, rb = scores[ia], scores[ib]
            # Skip ties
            if abs(ra - rb) < 0.05:
                continue
            # Ensure spA is the preferred (higher score)
            if ra < rb:
                ia, ib = ib, ia
                ra, rb = rb, ra

            spa = sp_list.iloc[ia]
            spb = sp_list.iloc[ib]
            row = {}
            for k, v in sc_feat.items():
                row[f"sc_{k}"] = v
            for col in SPECIES_FEATURE_COLS:
                row[f"a_{col}"] = float(spa[col])
                row[f"b_{col}"] = float(spb[col])
                row[f"d_{col}"] = float(spa[col]) - float(spb[col])
            row["score_diff"] = float(ra - rb)
            rows.append(row)
            labels.append(1)
            # Flip pair → negative example
            row2 = {}
            for k, v in sc_feat.items():
                row2[f"sc_{k}"] = v
            for col in SPECIES_FEATURE_COLS:
                row2[f"a_{col}"] = float(spb[col])
                row2[f"b_{col}"] = float(spa[col])
                row2[f"d_{col}"] = float(spb[col]) - float(spa[col])
            row2["score_diff"] = float(rb - ra)
            rows.append(row2)
            labels.append(0)

    X = pd.DataFrame(rows)
    return X, np.array(labels, dtype=np.int32)


# ─────────────────────────────────────────────────────────────────────────────
# 5. Train helpers
# ─────────────────────────────────────────────────────────────────────────────

def train_regressor(X_tr, y_tr, X_val, y_val, name: str):
    print(f"\n[{name}] training GBT regressor — {len(X_tr)} train / {len(X_val)} val rows …")
    model = GradientBoostingRegressor(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.85,
        min_samples_leaf=10,
        random_state=42,
        validation_fraction=0.1,
        n_iter_no_change=20,
        tol=1e-4,
    )
    model.fit(X_tr, y_tr)
    pred_tr  = model.predict(X_tr)
    pred_val = model.predict(X_val)
    metrics = {
        "train_mae":  float(mean_absolute_error(y_tr, pred_tr)),
        "train_rmse": float(mean_squared_error(y_tr, pred_tr) ** 0.5),
        "val_mae":    float(mean_absolute_error(y_val, pred_val)),
        "val_rmse":   float(mean_squared_error(y_val, pred_val) ** 0.5),
        "n_estimators_used": int(model.n_estimators_),
    }
    print(f"  train MAE={metrics['train_mae']:.4f} RMSE={metrics['train_rmse']:.4f} "
          f"| val MAE={metrics['val_mae']:.4f} RMSE={metrics['val_rmse']:.4f}")
    return model, metrics


def train_classifier(X_tr, y_tr, X_val, y_val, name: str):
    print(f"\n[{name}] training GBT classifier — {len(X_tr)} train / {len(X_val)} val rows …")
    model = GradientBoostingClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.85,
        min_samples_leaf=10,
        random_state=42,
        validation_fraction=0.1,
        n_iter_no_change=20,
        tol=1e-4,
    )
    model.fit(X_tr, y_tr)
    pred_val  = model.predict(X_val)
    prob_val  = model.predict_proba(X_val)[:, 1]
    metrics = {
        "val_accuracy": float(accuracy_score(y_val, pred_val)),
        "val_roc_auc":  float(roc_auc_score(y_val, prob_val)),
        "n_estimators_used": int(model.n_estimators_),
    }
    print(f"  val accuracy={metrics['val_accuracy']:.4f} AUC={metrics['val_roc_auc']:.4f}")
    return model, metrics


# ─────────────────────────────────────────────────────────────────────────────
# 6. Model artifact saving + registry update
# ─────────────────────────────────────────────────────────────────────────────

def save_model(
    model,
    metrics: dict,
    feature_cols: list[str],
    task: str,
    model_name: str,
    out_dir: Path,
    hyperparams: dict,
    n_train: int,
    n_val: int,
    species_csv_path: str,
) -> dict:
    model_dir = out_dir / model_name
    model_dir.mkdir(parents=True, exist_ok=True)
    model_path = model_dir / "model.joblib"
    meta_path  = model_dir / "metadata.json"

    joblib.dump({"model": model, "feature_cols": feature_cols}, model_path)

    meta = {
        "model_name":    model_name,
        "task":          task,
        "version":       "v1.0",
        "trained_at":    datetime.now(timezone.utc).isoformat(),
        "n_train":       n_train,
        "n_val":         n_val,
        "feature_cols":  feature_cols,
        "metrics":       metrics,
        "hyperparams":   hyperparams,
        "data_sources":  ["rule_based_species_catalog", species_csv_path],
        "framework":     "sklearn.GradientBoosting",
        "notes":         "Trained on synthetic (scenario × species) data generated from rule-based scoring logic.",
    }
    meta_path.write_text(json.dumps(meta, indent=2))
    print(f"  → saved: {model_path}")
    return {
        "model_path": str(model_path),
        "meta_path":  str(meta_path),
        "metrics":    metrics,
        "feature_cols": feature_cols,
        "task":       task,
        "model_name": model_name,
        "version":    "v1.0",
    }


def update_registry(registry_dir: Path, entries: list[dict], species_csv_path: str):
    idx_path = registry_dir / "registry_index.json"
    if idx_path.exists():
        data = json.loads(idx_path.read_text())
    else:
        data = {"models": []}

    now = datetime.now(timezone.utc).isoformat()
    for e in entries:
        record = {
            "model_id":              f"{e['model_name']}-v1",
            "model_name":            e["model_name"],
            "task":                  e["task"],
            "version":               e["version"],
            "status":                "production",
            "trained_at":            now,
            "training_snapshot_id":  "rule_based_species_v1",
            "artifact_paths": {
                "model":    e["model_path"],
                "metadata": e["meta_path"],
            },
            "training_code_version": "train_species_recommender.py@v1",
            "data_sources_used":     ["rule_based_species_catalog", species_csv_path],
            "source_mix_summary": {
                "synthetic_rule_based_pct": 100,
                "live_telemetry_pct":       0,
            },
            "metrics_summary":  e["metrics"],
            "feature_count":    len(e["feature_cols"]),
            "hyperparams": {
                "n_estimators": 200,
                "max_depth":    5,
                "learning_rate": 0.05,
            },
        }
        # Replace or append
        existing = [m for m in data["models"] if m["model_name"] == e["model_name"]]
        if existing:
            idx = data["models"].index(existing[0])
            data["models"][idx] = record
        else:
            data["models"].append(record)

    idx_path.write_text(json.dumps(data, indent=2))
    print(f"\n✓ Registry updated: {idx_path}  ({len(data['models'])} models total)")


# ─────────────────────────────────────────────────────────────────────────────
# 7. Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Train HeatWise species recommender from rule-based catalog")
    parser.add_argument("--species-csv", default=None,
                        help="Path to species_features.csv (auto-detected if omitted)")
    parser.add_argument("--out-dir", default=None,
                        help="Artifact output directory (default: registry/artifacts)")
    parser.add_argument("--registry-dir", default=None,
                        help="Registry index directory (default: registry/)")
    parser.add_argument("--n-scenarios", type=int, default=3000,
                        help="Number of synthetic scenarios to generate (default: 3000)")
    parser.add_argument("--pairs-per-scenario", type=int, default=8,
                        help="Pairwise sample pairs per scenario for ranker (default: 8)")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    # ── Resolve paths ─────────────────────────────────────────────────────────
    HERE = Path(__file__).resolve().parent
    ML   = HERE.parent

    species_csv = Path(args.species_csv) if args.species_csv else (
        ML / "data/bootstrap/sample_outputs/demo_pack/species_features.csv"
    )
    out_dir      = Path(args.out_dir)      if args.out_dir      else (ML / "registry/artifacts")
    registry_dir = Path(args.registry_dir) if args.registry_dir else (ML / "registry")

    if not species_csv.exists():
        print(f"ERROR: species CSV not found: {species_csv}", file=sys.stderr)
        sys.exit(1)

    print("=" * 64)
    print("HeatWise Species Recommender — Rule-Based ML Training")
    print("=" * 64)
    print(f"  Species CSV   : {species_csv}")
    print(f"  Scenarios     : {args.n_scenarios}")
    print(f"  Artifact dir  : {out_dir}")
    print(f"  Registry      : {registry_dir}")

    rng = random.Random(args.seed)
    np.random.seed(args.seed)

    # ── Load species ──────────────────────────────────────────────────────────
    print(f"\n[data] loading species catalog …")
    species_df = load_species(species_csv)
    print(f"  {len(species_df)} species × {len(SPECIES_FEATURE_COLS)} features")

    # ── Generate scenarios ────────────────────────────────────────────────────
    print(f"\n[data] generating {args.n_scenarios} scenarios …")
    scenarios = generate_scenarios(args.n_scenarios, rng)

    # ── Build regression dataset (scorer + heat_scorer) ───────────────────────
    print(f"\n[data] building regression dataset ({args.n_scenarios} × {len(species_df)} = "
          f"{args.n_scenarios * len(species_df)} rows) …")
    X_reg, y_rel, y_heat = build_regression_dataset(species_df, scenarios)
    X_reg_tr, X_reg_val, y_rel_tr, y_rel_val, y_heat_tr, y_heat_val = train_test_split(
        X_reg, y_rel, y_heat, test_size=0.15, random_state=args.seed
    )
    print(f"  train={len(X_reg_tr)} | val={len(X_reg_val)}")

    # ── Build pairwise dataset (ranker) ───────────────────────────────────────
    print(f"\n[data] building pairwise dataset …")
    # Use subset of scenarios for pairwise (enough for good coverage)
    pair_scenarios = scenarios[:min(args.n_scenarios, 1500)]
    X_pair, y_pair = build_pairwise_dataset(
        species_df, pair_scenarios, rng, pairs_per_scenario=args.pairs_per_scenario
    )
    X_pair_tr, X_pair_val, y_pair_tr, y_pair_val = train_test_split(
        X_pair, y_pair, test_size=0.15, random_state=args.seed
    )
    print(f"  pairwise train={len(X_pair_tr)} | val={len(X_pair_val)}")

    all_entries = []
    reg_feat_cols = list(X_reg.columns)
    pair_feat_cols = list(X_pair.columns)

    # ── Train 1: species_scorer ───────────────────────────────────────────────
    scorer_model, scorer_metrics = train_regressor(
        X_reg_tr, y_rel_tr, X_reg_val, y_rel_val, name="species_scorer"
    )
    all_entries.append(save_model(
        scorer_model, scorer_metrics, reg_feat_cols,
        task="species_relevance_regression",
        model_name="species_scorer",
        out_dir=out_dir,
        hyperparams={"n_estimators": 200, "max_depth": 5, "learning_rate": 0.05},
        n_train=len(X_reg_tr), n_val=len(X_reg_val),
        species_csv_path=str(species_csv),
    ))

    # ── Train 2: heat_scorer ──────────────────────────────────────────────────
    heat_model, heat_metrics = train_regressor(
        X_reg_tr, y_heat_tr, X_reg_val, y_heat_val, name="heat_scorer"
    )
    all_entries.append(save_model(
        heat_model, heat_metrics, reg_feat_cols,
        task="heat_mitigation_regression",
        model_name="heat_scorer",
        out_dir=out_dir,
        hyperparams={"n_estimators": 200, "max_depth": 5, "learning_rate": 0.05},
        n_train=len(X_reg_tr), n_val=len(X_reg_val),
        species_csv_path=str(species_csv),
    ))

    # ── Train 3: species_ranker ───────────────────────────────────────────────
    ranker_model, ranker_metrics = train_classifier(
        X_pair_tr, y_pair_tr, X_pair_val, y_pair_val, name="species_ranker"
    )
    all_entries.append(save_model(
        ranker_model, ranker_metrics, pair_feat_cols,
        task="species_pairwise_ranking",
        model_name="species_ranker",
        out_dir=out_dir,
        hyperparams={"n_estimators": 200, "max_depth": 5, "learning_rate": 0.05},
        n_train=len(X_pair_tr), n_val=len(X_pair_val),
        species_csv_path=str(species_csv),
    ))

    # ── Update registry ───────────────────────────────────────────────────────
    update_registry(registry_dir, all_entries, str(species_csv))

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "=" * 64)
    print("Training complete.")
    print("=" * 64)
    for e in all_entries:
        m = e["metrics"]
        if "val_roc_auc" in m:
            print(f"  {e['model_name']:20s}  acc={m['val_accuracy']:.4f}  AUC={m['val_roc_auc']:.4f}")
        else:
            print(f"  {e['model_name']:20s}  val_MAE={m['val_mae']:.4f}  val_RMSE={m['val_rmse']:.4f}")
    print()


if __name__ == "__main__":
    main()
